import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const body = await req.json();
    const { customer_name, phone, address, variant_id, quantity } = body;

    // Validation
    if (!customer_name || customer_name.trim().length < 2) {
      return new Response(
        JSON.stringify({ success: false, message: "নাম কমপক্ষে ২ অক্ষর হতে হবে" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    if (!phone || !/^01[3-9]\d{8}$/.test(phone.trim())) {
      return new Response(
        JSON.stringify({ success: false, message: "সঠিক বাংলাদেশি ফোন নম্বর দিন (01XXXXXXXXX)" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    if (!address || address.trim().length < 5) {
      return new Response(
        JSON.stringify({ success: false, message: "সম্পূর্ণ ঠিকানা দিন (কমপক্ষে ৫ অক্ষর)" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    if (!variant_id) {
      return new Response(
        JSON.stringify({ success: false, message: "পণ্যের সাইজ নির্বাচন করুন" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const qty = Number(quantity);
    if (!qty || qty < 1 || qty > 20) {
      return new Response(
        JSON.stringify({ success: false, message: "পরিমাণ ১-২০ এর মধ্যে হতে হবে" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Use service role to bypass RLS for reading variant + inserting order
    const supabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
    );

    // Fetch variant
    const { data: variant, error: variantError } = await supabase
      .from("product_variants")
      .select("id, name, price, stock_qty, is_active")
      .eq("id", variant_id)
      .eq("is_active", true)
      .single();

    if (variantError || !variant) {
      return new Response(
        JSON.stringify({ success: false, message: "এই পণ্যটি পাওয়া যায়নি" }),
        { status: 404, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    if (variant.stock_qty < qty) {
      return new Response(
        JSON.stringify({ success: false, message: "দুঃখিত, পর্যাপ্ত স্টক নেই" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const unit_price = variant.price;
    const total_price = unit_price * qty;

    // Insert order (order_ref auto-generated by trigger, stock reduced by trigger)
    const { data: order, error: orderError } = await supabase
      .from("orders")
      .insert({
        customer_name: customer_name.trim(),
        phone: phone.trim(),
        address: address.trim(),
        variant_id,
        quantity: qty,
        unit_price,
        total_price,
        order_ref: "temp", // Will be overwritten by trigger
      })
      .select("id, order_ref, customer_name, phone, address, quantity, unit_price, total_price, status, created_at")
      .single();

    if (orderError) {
      console.error("Order creation error:", orderError);
      if (orderError.message.includes("Insufficient stock")) {
        return new Response(
          JSON.stringify({ success: false, message: "দুঃখিত, পর্যাপ্ত স্টক নেই" }),
          { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      throw orderError;
    }

    return new Response(
      JSON.stringify({
        success: true,
        message: "অর্ডার সফলভাবে সম্পন্ন হয়েছে!",
        data: {
          ...order,
          variant_name: variant.name,
        },
      }),
      { status: 201, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (err) {
    console.error("Unexpected error:", err);
    return new Response(
      JSON.stringify({ success: false, message: "সার্ভারে সমস্যা হয়েছে, আবার চেষ্টা করুন" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
